// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/livros.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vazio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vazio) Reset() {
	*x = Vazio{}
	mi := &file_proto_livros_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vazio) ProtoMessage() {}

func (x *Vazio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livros_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vazio.ProtoReflect.Descriptor instead.
func (*Vazio) Descriptor() ([]byte, []int) {
	return file_proto_livros_proto_rawDescGZIP(), []int{0}
}

type LivroID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivroID) Reset() {
	*x = LivroID{}
	mi := &file_proto_livros_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivroID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivroID) ProtoMessage() {}

func (x *LivroID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livros_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivroID.ProtoReflect.Descriptor instead.
func (*LivroID) Descriptor() ([]byte, []int) {
	return file_proto_livros_proto_rawDescGZIP(), []int{1}
}

func (x *LivroID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Livro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor         string                 `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	Ano           int32                  `protobuf:"varint,4,opt,name=ano,proto3" json:"ano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Livro) Reset() {
	*x = Livro{}
	mi := &file_proto_livros_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Livro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Livro) ProtoMessage() {}

func (x *Livro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livros_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Livro.ProtoReflect.Descriptor instead.
func (*Livro) Descriptor() ([]byte, []int) {
	return file_proto_livros_proto_rawDescGZIP(), []int{2}
}

func (x *Livro) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Livro) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Livro) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *Livro) GetAno() int32 {
	if x != nil {
		return x.Ano
	}
	return 0
}

type ListaLivros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Livros        []*Livro               `protobuf:"bytes,1,rep,name=livros,proto3" json:"livros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaLivros) Reset() {
	*x = ListaLivros{}
	mi := &file_proto_livros_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaLivros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaLivros) ProtoMessage() {}

func (x *ListaLivros) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livros_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaLivros.ProtoReflect.Descriptor instead.
func (*ListaLivros) Descriptor() ([]byte, []int) {
	return file_proto_livros_proto_rawDescGZIP(), []int{3}
}

func (x *ListaLivros) GetLivros() []*Livro {
	if x != nil {
		return x.Livros
	}
	return nil
}

type LivroResposta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivroResposta) Reset() {
	*x = LivroResposta{}
	mi := &file_proto_livros_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivroResposta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivroResposta) ProtoMessage() {}

func (x *LivroResposta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_livros_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivroResposta.ProtoReflect.Descriptor instead.
func (*LivroResposta) Descriptor() ([]byte, []int) {
	return file_proto_livros_proto_rawDescGZIP(), []int{4}
}

func (x *LivroResposta) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

var File_proto_livros_proto protoreflect.FileDescriptor

const file_proto_livros_proto_rawDesc = "" +
	"\n" +
	"\x12proto/livros.proto\x12\x06livros\"\a\n" +
	"\x05Vazio\"\x19\n" +
	"\aLivroID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"W\n" +
	"\x05Livro\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x03 \x01(\tR\x05autor\x12\x10\n" +
	"\x03ano\x18\x04 \x01(\x05R\x03ano\"4\n" +
	"\vListaLivros\x12%\n" +
	"\x06livros\x18\x01 \x03(\v2\r.livros.LivroR\x06livros\"+\n" +
	"\rLivroResposta\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagem2\xa9\x01\n" +
	"\fLivroService\x122\n" +
	"\fListarLivros\x12\r.livros.Vazio\x1a\x13.livros.ListaLivros\x126\n" +
	"\x0eAdicionarLivro\x12\r.livros.Livro\x1a\x15.livros.LivroResposta\x12-\n" +
	"\vBuscarLivro\x12\x0f.livros.LivroID\x1a\r.livros.LivroB\x1dZ\x1bcatalogo-livros/proto;protob\x06proto3"

var (
	file_proto_livros_proto_rawDescOnce sync.Once
	file_proto_livros_proto_rawDescData []byte
)

func file_proto_livros_proto_rawDescGZIP() []byte {
	file_proto_livros_proto_rawDescOnce.Do(func() {
		file_proto_livros_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_livros_proto_rawDesc), len(file_proto_livros_proto_rawDesc)))
	})
	return file_proto_livros_proto_rawDescData
}

var file_proto_livros_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_livros_proto_goTypes = []any{
	(*Vazio)(nil),         // 0: livros.Vazio
	(*LivroID)(nil),       // 1: livros.LivroID
	(*Livro)(nil),         // 2: livros.Livro
	(*ListaLivros)(nil),   // 3: livros.ListaLivros
	(*LivroResposta)(nil), // 4: livros.LivroResposta
}
var file_proto_livros_proto_depIdxs = []int32{
	2, // 0: livros.ListaLivros.livros:type_name -> livros.Livro
	0, // 1: livros.LivroService.ListarLivros:input_type -> livros.Vazio
	2, // 2: livros.LivroService.AdicionarLivro:input_type -> livros.Livro
	1, // 3: livros.LivroService.BuscarLivro:input_type -> livros.LivroID
	3, // 4: livros.LivroService.ListarLivros:output_type -> livros.ListaLivros
	4, // 5: livros.LivroService.AdicionarLivro:output_type -> livros.LivroResposta
	2, // 6: livros.LivroService.BuscarLivro:output_type -> livros.Livro
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_livros_proto_init() }
func file_proto_livros_proto_init() {
	if File_proto_livros_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_livros_proto_rawDesc), len(file_proto_livros_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_livros_proto_goTypes,
		DependencyIndexes: file_proto_livros_proto_depIdxs,
		MessageInfos:      file_proto_livros_proto_msgTypes,
	}.Build()
	File_proto_livros_proto = out.File
	file_proto_livros_proto_goTypes = nil
	file_proto_livros_proto_depIdxs = nil
}
